name: todo_list
description: A Todo List Flutter project.

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# The version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"  # Updated to support null safety and Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  # Adds the Cupertino Icons font to your application for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  roundcheckbox: ^2.0.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  fluttertoast: ^8.0.7
  flutter_local_notifications: ^6.0.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.7
  table_calendar: ^3.0.2
  google_mobile_ads: ^0.13.5
  provider: ^6.0.1
  application_icon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.4

flutter_native_splash:
  color: "#ffffff"
  image: images/check-list.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/app_icon.png
